services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-spring-event
    ports:
      - "${PORT}:8080"
    environment:
      - spring.config.location=/usr/local/tomcat/webapps/application.properties
    volumes:
      - ./src/main/resources/application.properties:/usr/local/tomcat/webapps/application.properties 
    restart: always
